export const theme: any = {
  colors: {
    primary: {
      base: "#009fda",
      light: "#6ba8d0",
      lighter: "#cce5ff",
      pale: "#dbe8f3",
      dark: "#0075b0",
      darker: "#005c84",
    },
    secondary: {
      base: "#6ac07a",
      light: "#9dd29c",
      lighter: "#9dd29c",
      pale: "#c3e2c1",
      dark: "#69be28",
      darker: "#3f9c35",
    },
    info: {
      base: "#17a2b8",
      light: "#5bc0de",
      lighter: "#d1ecf1",
      pale: "#e9f7fc",
      dark: "#117a8b",
      darker: "#0b5964",
    },
    success: {
      base: "#28a745",
      light: "#71dd81",
      lighter: "#d4edda",
      pale: "#eafaf1",
      dark: "#1e7b34",
      darker: "#155724",
    },
    warning: {
      base: "#ffc107",
      light: "#ffe380",
      lighter: "#fff3cd",
      pale: "#fff8e5",
      dark: "#e0a800",
      darker: "#ff991f",
    },
    danger: {
      base: "#dc3545",
      light: "#f28b8b",
      lighter: "#f8d7da",
      pale: "#fbe7e9",
      dark: "#a71d2a",
      darker: "#7b131e",
    },
    default: {
      base: "#939598",
      light: "#bcbec0",
      lighter: "#ededed",
      pale: "#e1e1e1",
      dark: "#6d6e71",
      darker: "#202020",
    },
    lightA: "#f2f2f2",
    lightB: "#f8f8f8",
  },
  sizes: {
    label: {
      xs: 10,
      sm: 10,
      md: 12,
      lg: 14,
      xl: 16,
    },
    fontSize: {
      xs: 12,
      sm: 12,
      md: 14,
      lg: 16,
      xl: 16,
    },
    boxSize: {
      xs: 18,
      sm: 24,
      md: 32,
      lg: 40,
      xl: 48,
    },
    buttonPadding: {
      xs: "3px 8px",
      sm: "6px 10px",
      md: "9px 14px",
      lg: "12px 18px",
      xl: "16px 20px",
    },
  },
  fontFamily:
    '"Nunito Sans", -apple-system, ".SFNSText-Regular", "San Francisco", BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Helvetica, Arial, sans-serif',
  transition: "all .3s ease",
};
