export const FIELD_SETTINGS = [
  {
    header: "General Details",
    fields: [
      {
        name: "ackNumber",
        label: "Acknowledgement Number",
        type: "number",
        placeholder: "Enter acknowledgement number",
        validation: (z: any) =>
          z.number().positive("Acknowledgement number is mandatory"),
      },
      {
        name: "submissionMode",
        label: "Submission Mode",
        type: "select", // align to server label mapping
        options: [
          { label: "TNG - Trade Nextgen", value: "TNG - Trade Nextgen" },
          { label: "EML - Email", value: "EML - Email" },
          { label: "OTC - Over the Counter", value: "OTC - Over the Counter" },
        ],
        placeholder: "Select submission mode",
        validation: (z: any) =>
          z.string().required("Submission Mode is mandatory"),
      },
      // The rest are override-backed fields; server will echo them back via buildGeneral(...)
      {
        name: "financeType",
        label: "Finance Type",
        type: "text",
        placeholder: "e.g., EIF - Export Invoice Financing",
        validation: (z: any) =>
          z.string().required("Finance Type is mandatory"),
      },
      {
        name: "productGroup",
        label: "Product Group",
        type: "text",
        placeholder: "e.g., RF - Receivable finance",
        validation: (z: any) =>
          z.string().required("Product Group is mandatory"),
      },
      {
        name: "btcId",
        label: "BTC ID",
        type: "text",
        placeholder: "SG01xxxxxxxxEIF0101",
      },
      {
        name: "limitGroupId",
        label: "Limit Group ID",
        type: "text",
        placeholder: "e.g., 1 - GTF-Default",
        validation: (z: any) =>
          z.string().required("Limit Group ID is mandatory"),
      },
      {
        name: "valueDateOption",
        label: "Value Date Option",
        type: "text",
        placeholder: "e.g., PD - PROCESSING DATE",
        validation: (z: any) =>
          z.string().required("Value Date Option is mandatory"),
      },
      {
        name: "valueDate",
        label: "Value Date",
        type: "text",
        placeholder: "DD-MMM-YYYY",
      },
      {
        name: "summaryListing",
        label: "Summary Listing",
        type: "text",
        placeholder: "e.g., SML01 - Allowed",
      },
      {
        name: "submissionBranch",
        label: "Submission Branch",
        type: "select", // must be code; server maps code -> full name
        options: [
          { label: "SG01", value: "SG01" },
          { label: "MY01", value: "MY01" },
          { label: "HK01", value: "HK01" },
        ],
        placeholder: "Select Submission Branch",
      },
      {
        name: "clientReference",
        label: "Client Reference",
        type: "text",
        placeholder: "Enter client reference",
      },
      {
        name: "emailIndemnityHeld",
        label: "Email Indemnity Held",
        type: "select",
        options: [
          { label: "Required", value: "Required" },
          { label: "Not Required", value: "Not Required" },
        ],
        placeholder: "Select Option",
      },
      {
        name: "isIslamicTransaction",
        label: "Islamic Transaction",
        type: "checkbox",
      },
      { name: "reviewFlag", label: "Review Flag", type: "checkbox" },
      {
        name: "almApprovalReceived",
        label: "ALM Approval Received",
        type: "checkbox",
      },
      {
        name: "clientRemarks",
        label: "Client Remarks",
        type: "textarea",
        rows: 4,
        placeholder: "Enter Client Remarks..",
      },
      {
        name: "counterparty",
        label: "Counter Party",
        type: "text",
        placeholder: "Enter counterparty",
      },
      {
        name: "signatureVerified",
        label: "Signature Verification",
        type: "checkbox",
      },
    ],
  },
];

export const VALUES = {
  ackNumber: 2500000,
  submissionMode: "EML - Email",
  financeType: "EIF - Export Invoice Financing",
  productGroup: "RF - Receivable finance",
  btcId: "SG01100006898EIF0101",
  limitGroupId: "1 - GTF-Default",
  valueDateOption: "PD - PROCESSING DATE",
  valueDate: "30-Mar-2018",
  summaryListing: "SML01 - Allowed",
  submissionBranch: "SG01",
  clientReference: "NG-Adaptor-IIF6",
  isIslamicTransaction: false,
  reviewFlag: false,
  almApprovalReceived: false,
  emailIndemnityHeld: "Not Required",
  clientRemarks: "",
  signatureVerified: false,
  counterparty: "PHARMA MED",
};

export const COLUMN_SETTINGS = [
  {
    column: "arn",
    title: "ARN #",
    minWidth: 120,
    pin: "pin",
    filter: {
      type: "text",
    },
  },
  {
    column: "trn",
    title: "TRN #",
    minWidth: 180,
    pin: "pin",
  },
  {
    column: "customer",
    title: "CUSTOMER",
    minWidth: 280,
  },
  {
    column: "counterparty",
    title: "COUNTERPARTY",
    minWidth: 160,
  },
  {
    column: "product",
    title: "PRODUCT",
    minWidth: 80,
  },
  {
    column: "step",
    title: "STEP",
    minWidth: 100,
  },
  {
    column: "subStep",
    title: "SUB STEP",
    minWidth: 110,
  },
  {
    column: "lockedBy",
    title: "LOCKED BY",
    minWidth: 110,
  },
  {
    column: "stage",
    title: "STAGE",
    minWidth: 260,
  },
  {
    groupTitle: "COMPLIANCE STATUS",
    column: "lli",
    title: "LLI",
    draggable: false,
    width: 75,
    headerAlign: "center",
    align: "center",
  },
  {
    groupTitle: "COMPLIANCE STATUS",
    column: "aml",
    title: "AML",
    draggable: false,
    width: 75,
    headerAlign: "center",
    align: "center",
  },
  {
    groupTitle: "COMPLIANCE STATUS",
    column: "snc",
    title: "SNC",
    draggable: false,
    width: 75,
    headerAlign: "center",
    align: "center",
  },
  {
    groupTitle: "COMPLIANCE STATUS",
    column: "clbk",
    title: "CLBK",
    draggable: false,
    width: 80,
    headerAlign: "center",
    align: "center",
  },
  {
    groupTitle: "COMPLIANCE STATUS",
    column: "cocoa",
    title: "COCOA",
    draggable: false,
    width: 90,
    headerAlign: "center",
    align: "center",
  },
  {
    groupTitle: "COMPLIANCE STATUS",
    column: "tdOpsApproval",
    title: "TD OPS APPROVAL",
    draggable: false,
    width: 155,
    headerAlign: "center",
    align: "center",
  },
  {
    column: "customerRef",
    title: "CUSTOMER REFERENCE",
    minWidth: 200,
  },
  {
    column: "submissionMode",
    title: "SUBMISSION MODE",
    minWidth: 140,
  },
  {
    column: "regDate",
    title: "REG. DATE",
    minWidth: 160,
  },
  {
    column: "relDate",
    title: "REL. DATE",
    minWidth: 160,
  },
  {
    column: "createdAt",
    title: "Creaetd At",
    minWidth: 160,
  },
  {
    column: "segment",
    title: "SEGMENT",
    width: 90,
    align: "center",
  },
  {
    column: "subSegment",
    title: "SUB SEGMENT",
    width: 120,
    align: "center",
  },
  {
    column: "splitId",
    title: "SPLIT ID",
    width: 100,
    align: "right",
  },
  {
    column: "__actions",
    title: "",
    width: 110,
    align: "center",
  },
];

export const DATA_SOURCE = {
  rows: [
    {
      id: 1,
      arn: "2500000",
      bookingLocation: "Standard Chartered Bank (Singapore) Ltd",
      workflowStage: "SPLCP - Split Completed",
      submissionMode: "EML",
      receivedAt: "2018-03-30T05:10:35.000Z",
      __receivedAtMs: 1522386635000,
      createdAt: "2018-03-30T05:10:35.000Z",
      __createdAtMs: 1522386635000,
      updatedAt: "2018-03-30T05:10:35.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003129",
      customer: "100006898 - TXOPT TESTING LONG NAME COMPANY LTD",
      counterparty: "PHARMA MED",
      product: "EIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201231",
      stage: "EXEMK - Exception Handling Maker",
      lli: "ZEKE",
      aml: "BOLT",
      snc: "ECHO",
      clbk: "RISK",
      cocoa: "ZEKE",
      tdOpsApproval: "NULL",
      customerRef: "NG-Adaptor-IIF6",
      regDate: "2018-03-30",
      relDate: "2018-03-30",
      segment: "ME",
      subSegment: "03",
      splitId: "251",
      sustainable: {
        sustainableFlag: true,
        classification: "OTHERS",
        empoweredStatus: true,
        empoweredDate: "2018-03-30",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "1-1",
          code: "E014",
          description: "Auto-generated exception E014 for TRN SPBTR25RFC003129",
          department: "Compliance",
        },
        {
          id: "1-2",
          code: "E055",
          description: "Auto-generated exception E055 for TRN SPBTR25RFC003129",
          department: "Front Office",
        },
        {
          id: "1-3",
          code: "E078",
          description: "Auto-generated exception E078 for TRN SPBTR25RFC003129",
          department: "Credit Control",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "SGD",
        batchAmount: 1979.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "SGD",
        maxEligibleAmount: 1781.15,
        batchAdjustmentCurrency: "SGD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2018-03-30",
        statementDate: "2018-03-30",
        manualLLITrigger: false,
        documentNumber: "EIF_1_100xxxxxxxx",
        documentAmountCurrency: "SGD",
        documentAmount: 1979.05,
        adjustmentAmountCurrency: "SGD",
        adjustmentAmount: 0,
        counterpartyName: "PHARMA MED",
        documentIssueDate: "2018-03-30",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2018-04-06",
        incoterms: "FOB",
        eligibleAmountCurrency: "SGD",
        eligibleAmount: 1781.15,
        maxMaturityDate: "2018-04-06",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_1_100xxxxxxxx",
            currency: "SGD",
            amount: 1979.05,
            issueDate: "2018-03-30",
            dueDate: "2018-04-06",
            eligibleAmt: 1781.15,
            maxMaturityDate: "2018-04-06",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 2,
      arn: "2500001",
      bookingLocation: "KUALA LUMPUR 284484",
      workflowStage: "SPLIN - Split Initiated",
      submissionMode: "TNG",
      receivedAt: "2025-09-24T05:20:37.000Z",
      __receivedAtMs: 1758691237000,
      createdAt: "2025-09-24T05:20:37.000Z",
      __createdAtMs: 1758691237000,
      updatedAt: "2025-09-24T05:20:37.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003130",
      customer: "100009999 - SAMPLE INDUSTRIES PTE LTD",
      counterparty: "100502577 - TEST",
      product: "IIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201232",
      stage: "PRINP - Processing In-Progress",
      lli: "BOLT",
      aml: "ECHO",
      snc: "RISK",
      clbk: "ZEKE",
      cocoa: "BOLT",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2025-09-23",
      relDate: "2025-09-24",
      segment: "ME",
      subSegment: "03",
      splitId: "252",
      sustainable: {
        sustainableFlag: null,
        classification: "",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "MYR",
        batchAmount: 1980.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "MYR",
        maxEligibleAmount: 1782.05,
        batchAdjustmentCurrency: "MYR",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2025-09-24",
        statementDate: "2025-09-24",
        manualLLITrigger: false,
        documentNumber: "EIF_2_100xxxxxxxx",
        documentAmountCurrency: "MYR",
        documentAmount: 1980.05,
        adjustmentAmountCurrency: "MYR",
        adjustmentAmount: 0,
        counterpartyName: "100502577 - TEST",
        documentIssueDate: "2025-09-24",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2025-10-01",
        incoterms: "FOB",
        eligibleAmountCurrency: "MYR",
        eligibleAmount: 1782.05,
        maxMaturityDate: "2025-10-01",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_2_100xxxxxxxx",
            currency: "MYR",
            amount: 1980.05,
            issueDate: "2025-09-24",
            dueDate: "2025-10-01",
            eligibleAmt: 1782.05,
            maxMaturityDate: "2025-10-01",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 3,
      arn: "2500002",
      bookingLocation: "SCB Hong Kong Ltd",
      workflowStage: "APRV - Approved",
      submissionMode: "OTC",
      receivedAt: "2025-03-27T06:28:04.000Z",
      __receivedAtMs: 1743056884000,
      createdAt: "2025-03-27T06:28:04.000Z",
      __createdAtMs: 1743056884000,
      updatedAt: "2025-03-27T06:28:04.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003131",
      customer: "100001111 - DEMO GROUP HOLDINGS",
      counterparty: "NG-Adaptor-IIF6",
      product: "SUF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201233",
      stage: "TXPMK - Transaction Pending Maker",
      lli: "ECHO",
      aml: "RISK",
      snc: "ZEKE",
      clbk: "BOLT",
      cocoa: "ECHO",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2025-03-27",
      relDate: "2025-03-27",
      segment: "ME",
      subSegment: "03",
      splitId: "253",
      sustainable: {
        sustainableFlag: true,
        classification: "TRANSITION",
        empoweredStatus: true,
        empoweredDate: "2025-03-27",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "3-1",
          code: "E078",
          description: "Auto-generated exception E078 for TRN SPBTR25RFC003131",
          department: "Trade Services",
        },
        {
          id: "3-2",
          code: "E014",
          description: "Auto-generated exception E014 for TRN SPBTR25RFC003131",
          department: "Front Office",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "HKD",
        batchAmount: 1981.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "HKD",
        maxEligibleAmount: 1782.95,
        batchAdjustmentCurrency: "HKD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2025-03-27",
        statementDate: "2025-03-27",
        manualLLITrigger: false,
        documentNumber: "EIF_3_100xxxxxxxx",
        documentAmountCurrency: "HKD",
        documentAmount: 1981.05,
        adjustmentAmountCurrency: "HKD",
        adjustmentAmount: 0,
        counterpartyName: "NG-Adaptor-IIF6",
        documentIssueDate: "2025-03-27",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2025-04-03",
        incoterms: "FOB",
        eligibleAmountCurrency: "HKD",
        eligibleAmount: 1782.95,
        maxMaturityDate: "2025-04-03",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_3_100xxxxxxxx",
            currency: "HKD",
            amount: 1981.05,
            issueDate: "2025-03-27",
            dueDate: "2025-04-03",
            eligibleAmt: 1782.95,
            maxMaturityDate: "2025-04-03",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 4,
      arn: "2500003",
      bookingLocation: "Standard Chartered Bank (Singapore) Ltd",
      workflowStage: "EXEMK - Exception Handling Maker",
      submissionMode: "EML",
      receivedAt: "2024-05-12T14:55:22.000Z",
      __receivedAtMs: 1715525722000,
      createdAt: "2024-05-12T14:55:22.000Z",
      __createdAtMs: 1715525722000,
      updatedAt: "2024-05-12T14:55:22.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003132",
      customer: "100006898 - TXOPT TESTING LONG NAME COMPANY LTD",
      counterparty: "PHARMA MED",
      product: "EIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201234",
      stage: "PPRMK - Pre Processing Maker",
      lli: "RISK",
      aml: "ZEKE",
      snc: "BOLT",
      clbk: "ECHO",
      cocoa: "RISK",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2024-05-12",
      relDate: "2024-05-13",
      segment: "ME",
      subSegment: "03",
      splitId: "254",
      sustainable: {
        sustainableFlag: null,
        classification: "",
        empoweredStatus: true,
        empoweredDate: "2024-05-12",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "4-1",
          code: "E063",
          description: "Auto-generated exception E063 for TRN SPBTR25RFC003132",
          department: "Credit Control",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "SGD",
        batchAmount: 1982.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "SGD",
        maxEligibleAmount: 1783.85,
        batchAdjustmentCurrency: "SGD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2024-05-12",
        statementDate: "2024-05-12",
        manualLLITrigger: false,
        documentNumber: "EIF_4_100xxxxxxxx",
        documentAmountCurrency: "SGD",
        documentAmount: 1982.05,
        adjustmentAmountCurrency: "SGD",
        adjustmentAmount: 0,
        counterpartyName: "PHARMA MED",
        documentIssueDate: "2024-05-12",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2024-05-19",
        incoterms: "FOB",
        eligibleAmountCurrency: "SGD",
        eligibleAmount: 1783.85,
        maxMaturityDate: "2024-05-19",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_4_100xxxxxxxx",
            currency: "SGD",
            amount: 1982.05,
            issueDate: "2024-05-12",
            dueDate: "2024-05-19",
            eligibleAmt: 1783.85,
            maxMaturityDate: "2024-05-19",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 5,
      arn: "2500004",
      bookingLocation: "SCB Malaysia Berhad",
      workflowStage: "PRINP - Processing In-Progress",
      submissionMode: "TNG",
      receivedAt: "2022-05-10T12:26:28.000Z",
      __receivedAtMs: 1652185588000,
      createdAt: "2022-05-10T12:26:28.000Z",
      __createdAtMs: 1652185588000,
      updatedAt: "2022-05-10T12:26:28.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003133",
      customer: "100009999 - SAMPLE INDUSTRIES PTE LTD",
      counterparty: "100502577 - TEST",
      product: "IIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201235",
      stage: "SPLCP - Split Completed",
      lli: "ZEKE",
      aml: "BOLT",
      snc: "ECHO",
      clbk: "RISK",
      cocoa: "ZEKE",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2022-05-10",
      relDate: "2022-05-11",
      segment: "ME",
      subSegment: "03",
      splitId: "255",
      sustainable: {
        sustainableFlag: true,
        classification: "GREEN",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "5-1",
          code: "E001",
          description: "Auto-generated exception E001 for TRN SPBTR25RFC003133",
          department: "Operations",
        },
        {
          id: "5-2",
          code: "E063",
          description: "Auto-generated exception E063 for TRN SPBTR25RFC003133",
          department: "Front Office",
        },
        {
          id: "5-3",
          code: "E027",
          description: "Auto-generated exception E027 for TRN SPBTR25RFC003133",
          department: "Compliance",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "MYR",
        batchAmount: 1983.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "MYR",
        maxEligibleAmount: 1784.75,
        batchAdjustmentCurrency: "MYR",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2022-05-10",
        statementDate: "2022-05-10",
        manualLLITrigger: false,
        documentNumber: "EIF_5_100xxxxxxxx",
        documentAmountCurrency: "MYR",
        documentAmount: 1983.05,
        adjustmentAmountCurrency: "MYR",
        adjustmentAmount: 0,
        counterpartyName: "100502577 - TEST",
        documentIssueDate: "2022-05-10",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2022-05-17",
        incoterms: "FOB",
        eligibleAmountCurrency: "MYR",
        eligibleAmount: 1784.75,
        maxMaturityDate: "2022-05-17",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_5_100xxxxxxxx",
            currency: "MYR",
            amount: 1983.05,
            issueDate: "2022-05-10",
            dueDate: "2022-05-17",
            eligibleAmt: 1784.75,
            maxMaturityDate: "2022-05-17",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 6,
      arn: "2500005",
      bookingLocation: "SCB Hong Kong Ltd",
      workflowStage: "TXPMK - Transaction Pending Maker",
      submissionMode: "OTC",
      receivedAt: "2019-11-28T08:07:56.000Z",
      __receivedAtMs: 1574928476000,
      createdAt: "2019-11-28T08:07:56.000Z",
      __createdAtMs: 1574928476000,
      updatedAt: "2019-11-28T08:07:56.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003134",
      customer: "100001111 - DEMO GROUP HOLDINGS",
      counterparty: "NG-Adaptor-IIF6",
      product: "SUF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201236",
      stage: "SPLIN - Split Initiated",
      lli: "BOLT",
      aml: "ECHO",
      snc: "RISK",
      clbk: "ZEKE",
      cocoa: "BOLT",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2019-11-28",
      relDate: "2019-11-28",
      segment: "ME",
      subSegment: "03",
      splitId: "256",
      sustainable: {
        sustainableFlag: true,
        classification: "SL",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "6-1",
          code: "E014",
          description: "Auto-generated exception E014 for TRN SPBTR25RFC003134",
          department: "Front Office",
        },
        {
          id: "6-2",
          code: "E014",
          description: "Auto-generated exception E014 for TRN SPBTR25RFC003134",
          department: "Compliance",
        },
        {
          id: "6-3",
          code: "E014",
          description: "Auto-generated exception E014 for TRN SPBTR25RFC003134",
          department: "Compliance",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "HKD",
        batchAmount: 1984.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "HKD",
        maxEligibleAmount: 1785.65,
        batchAdjustmentCurrency: "HKD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2019-11-28",
        statementDate: "2019-11-28",
        manualLLITrigger: false,
        documentNumber: "EIF_6_100xxxxxxxx",
        documentAmountCurrency: "HKD",
        documentAmount: 1984.05,
        adjustmentAmountCurrency: "HKD",
        adjustmentAmount: 0,
        counterpartyName: "NG-Adaptor-IIF6",
        documentIssueDate: "2019-11-28",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2019-12-05",
        incoterms: "FOB",
        eligibleAmountCurrency: "HKD",
        eligibleAmount: 1785.65,
        maxMaturityDate: "2019-12-05",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_6_100xxxxxxxx",
            currency: "HKD",
            amount: 1984.05,
            issueDate: "2019-11-28",
            dueDate: "2019-12-05",
            eligibleAmt: 1785.65,
            maxMaturityDate: "2019-12-05",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 7,
      arn: "2500006",
      bookingLocation: "Standard Chartered Bank (Singapore) Ltd",
      workflowStage: "PPRMK - Pre Processing Maker",
      submissionMode: "EML",
      receivedAt: "2019-05-21T06:06:16.000Z",
      __receivedAtMs: 1558418776000,
      createdAt: "2019-05-21T06:06:16.000Z",
      __createdAtMs: 1558418776000,
      updatedAt: "2019-05-21T06:06:16.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003135",
      customer: "100006898 - TXOPT TESTING LONG NAME COMPANY LTD",
      counterparty: "PHARMA MED",
      product: "EIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201237",
      stage: "APRV - Approved",
      lli: "ECHO",
      aml: "RISK",
      snc: "ZEKE",
      clbk: "BOLT",
      cocoa: "ECHO",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2019-05-21",
      relDate: "2019-05-22",
      segment: "ME",
      subSegment: "03",
      splitId: "257",
      sustainable: {
        sustainableFlag: null,
        classification: "",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "SGD",
        batchAmount: 1978.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "SGD",
        maxEligibleAmount: 1780.25,
        batchAdjustmentCurrency: "SGD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2019-05-21",
        statementDate: "2019-05-21",
        manualLLITrigger: false,
        documentNumber: "EIF_7_100xxxxxxxx",
        documentAmountCurrency: "SGD",
        documentAmount: 1978.05,
        adjustmentAmountCurrency: "SGD",
        adjustmentAmount: 0,
        counterpartyName: "PHARMA MED",
        documentIssueDate: "2019-05-21",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2019-05-28",
        incoterms: "FOB",
        eligibleAmountCurrency: "SGD",
        eligibleAmount: 1780.25,
        maxMaturityDate: "2019-05-28",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_7_100xxxxxxxx",
            currency: "SGD",
            amount: 1978.05,
            issueDate: "2019-05-21",
            dueDate: "2019-05-28",
            eligibleAmt: 1780.25,
            maxMaturityDate: "2019-05-28",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 8,
      arn: "2500007",
      bookingLocation: "SCB Malaysia Berhad",
      workflowStage: "SPLCP - Split Completed",
      submissionMode: "TNG",
      receivedAt: "2020-05-23T18:59:05.000Z",
      __receivedAtMs: 1590260345000,
      createdAt: "2020-05-23T18:59:05.000Z",
      __createdAtMs: 1590260345000,
      updatedAt: "2020-05-23T18:59:05.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003136",
      customer: "100009999 - SAMPLE INDUSTRIES PTE LTD",
      counterparty: "100502577 - TEST",
      product: "IIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201238",
      stage: "EXEMK - Exception Handling Maker",
      lli: "RISK",
      aml: "ZEKE",
      snc: "BOLT",
      clbk: "ECHO",
      cocoa: "RISK",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2020-05-23",
      relDate: "2020-05-24",
      segment: "ME",
      subSegment: "03",
      splitId: "258",
      sustainable: {
        sustainableFlag: false,
        classification: "",
        empoweredStatus: true,
        empoweredDate: "2020-05-23",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "MYR",
        batchAmount: 1979.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "MYR",
        maxEligibleAmount: 1781.15,
        batchAdjustmentCurrency: "MYR",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2020-05-23",
        statementDate: "2020-05-23",
        manualLLITrigger: false,
        documentNumber: "EIF_8_100xxxxxxxx",
        documentAmountCurrency: "MYR",
        documentAmount: 1979.05,
        adjustmentAmountCurrency: "MYR",
        adjustmentAmount: 0,
        counterpartyName: "100502577 - TEST",
        documentIssueDate: "2020-05-23",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2020-05-30",
        incoterms: "FOB",
        eligibleAmountCurrency: "MYR",
        eligibleAmount: 1781.15,
        maxMaturityDate: "2020-05-30",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_8_100xxxxxxxx",
            currency: "MYR",
            amount: 1979.05,
            issueDate: "2020-05-23",
            dueDate: "2020-05-30",
            eligibleAmt: 1781.15,
            maxMaturityDate: "2020-05-30",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 9,
      arn: "2500008",
      bookingLocation: "SCB Hong Kong Ltd",
      workflowStage: "SPLIN - Split Initiated",
      submissionMode: "OTC",
      receivedAt: "2019-12-28T07:32:59.000Z",
      __receivedAtMs: 1577518379000,
      createdAt: "2019-12-28T07:32:59.000Z",
      __createdAtMs: 1577518379000,
      updatedAt: "2019-12-28T07:32:59.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003137",
      customer: "100001111 - DEMO GROUP HOLDINGS",
      counterparty: "NG-Adaptor-IIF6",
      product: "SUF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201239",
      stage: "PRINP - Processing In-Progress",
      lli: "ZEKE",
      aml: "BOLT",
      snc: "ECHO",
      clbk: "RISK",
      cocoa: "ZEKE",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2019-12-28",
      relDate: "2019-12-28",
      segment: "ME",
      subSegment: "03",
      splitId: "259",
      sustainable: {
        sustainableFlag: null,
        classification: "",
        empoweredStatus: true,
        empoweredDate: "2019-12-28",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "9-1",
          code: "E027",
          description: "Auto-generated exception E027 for TRN SPBTR25RFC003137",
          department: "Operations",
        },
        {
          id: "9-2",
          code: "E001",
          description: "Auto-generated exception E001 for TRN SPBTR25RFC003137",
          department: "Trade Services",
        },
        {
          id: "9-3",
          code: "E027",
          description: "Auto-generated exception E027 for TRN SPBTR25RFC003137",
          department: "Credit Control",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "HKD",
        batchAmount: 1980.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "HKD",
        maxEligibleAmount: 1782.05,
        batchAdjustmentCurrency: "HKD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2019-12-28",
        statementDate: "2019-12-28",
        manualLLITrigger: false,
        documentNumber: "EIF_9_100xxxxxxxx",
        documentAmountCurrency: "HKD",
        documentAmount: 1980.05,
        adjustmentAmountCurrency: "HKD",
        adjustmentAmount: 0,
        counterpartyName: "NG-Adaptor-IIF6",
        documentIssueDate: "2019-12-28",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2020-01-04",
        incoterms: "FOB",
        eligibleAmountCurrency: "HKD",
        eligibleAmount: 1782.05,
        maxMaturityDate: "2020-01-04",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_9_100xxxxxxxx",
            currency: "HKD",
            amount: 1980.05,
            issueDate: "2019-12-28",
            dueDate: "2020-01-04",
            eligibleAmt: 1782.05,
            maxMaturityDate: "2020-01-04",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 10,
      arn: "2500009",
      bookingLocation: "Standard Chartered Bank (Singapore) Ltd",
      workflowStage: "APRV - Approved",
      submissionMode: "EML",
      receivedAt: "2021-03-30T09:49:10.000Z",
      __receivedAtMs: 1617097750000,
      createdAt: "2021-03-30T09:49:10.000Z",
      __createdAtMs: 1617097750000,
      updatedAt: "2021-03-30T09:49:10.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003138",
      customer: "100006898 - TXOPT TESTING LONG NAME COMPANY LTD",
      counterparty: "PHARMA MED",
      product: "EIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201240",
      stage: "TXPMK - Transaction Pending Maker",
      lli: "BOLT",
      aml: "ECHO",
      snc: "RISK",
      clbk: "ZEKE",
      cocoa: "BOLT",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2021-03-30",
      relDate: "2021-03-30",
      segment: "ME",
      subSegment: "03",
      splitId: "251",
      sustainable: {
        sustainableFlag: true,
        classification: "GREEN",
        empoweredStatus: true,
        empoweredDate: "2021-03-30",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "10-1",
          code: "E078",
          description: "Auto-generated exception E078 for TRN SPBTR25RFC003138",
          department: "Trade Services",
        },
        {
          id: "10-2",
          code: "E001",
          description: "Auto-generated exception E001 for TRN SPBTR25RFC003138",
          department: "Compliance",
        },
        {
          id: "10-3",
          code: "E001",
          description: "Auto-generated exception E001 for TRN SPBTR25RFC003138",
          department: "Operations",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "SGD",
        batchAmount: 1981.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "SGD",
        maxEligibleAmount: 1782.95,
        batchAdjustmentCurrency: "SGD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2021-03-30",
        statementDate: "2021-03-30",
        manualLLITrigger: false,
        documentNumber: "EIF_10_100xxxxxxxx",
        documentAmountCurrency: "SGD",
        documentAmount: 1981.05,
        adjustmentAmountCurrency: "SGD",
        adjustmentAmount: 0,
        counterpartyName: "PHARMA MED",
        documentIssueDate: "2021-03-30",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2021-04-06",
        incoterms: "FOB",
        eligibleAmountCurrency: "SGD",
        eligibleAmount: 1782.95,
        maxMaturityDate: "2021-04-06",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_10_100xxxxxxxx",
            currency: "SGD",
            amount: 1981.05,
            issueDate: "2021-03-30",
            dueDate: "2021-04-06",
            eligibleAmt: 1782.95,
            maxMaturityDate: "2021-04-06",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 11,
      arn: "2500010",
      bookingLocation: "SCB Malaysia Berhad",
      workflowStage: "EXEMK - Exception Handling Maker",
      submissionMode: "TNG",
      receivedAt: "2025-04-20T00:56:51.000Z",
      __receivedAtMs: 1745110611000,
      createdAt: "2025-04-20T00:56:51.000Z",
      __createdAtMs: 1745110611000,
      updatedAt: "2025-04-20T00:56:51.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003139",
      customer: "100009999 - SAMPLE INDUSTRIES PTE LTD",
      counterparty: "100502577 - TEST",
      product: "IIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201241",
      stage: "PPRMK - Pre Processing Maker",
      lli: "ECHO",
      aml: "RISK",
      snc: "ZEKE",
      clbk: "BOLT",
      cocoa: "ECHO",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2025-04-19",
      relDate: "2025-04-20",
      segment: "ME",
      subSegment: "03",
      splitId: "252",
      sustainable: {
        sustainableFlag: true,
        classification: "OTHERS",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "11-1",
          code: "E014",
          description: "Auto-generated exception E014 for TRN SPBTR25RFC003139",
          department: "Compliance",
        },
        {
          id: "11-2",
          code: "E027",
          description: "Auto-generated exception E027 for TRN SPBTR25RFC003139",
          department: "Operations",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "MYR",
        batchAmount: 1982.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "MYR",
        maxEligibleAmount: 1783.85,
        batchAdjustmentCurrency: "MYR",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2025-04-20",
        statementDate: "2025-04-20",
        manualLLITrigger: false,
        documentNumber: "EIF_11_100xxxxxxxx",
        documentAmountCurrency: "MYR",
        documentAmount: 1982.05,
        adjustmentAmountCurrency: "MYR",
        adjustmentAmount: 0,
        counterpartyName: "100502577 - TEST",
        documentIssueDate: "2025-04-20",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2025-04-27",
        incoterms: "FOB",
        eligibleAmountCurrency: "MYR",
        eligibleAmount: 1783.85,
        maxMaturityDate: "2025-04-27",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_11_100xxxxxxxx",
            currency: "MYR",
            amount: 1982.05,
            issueDate: "2025-04-20",
            dueDate: "2025-04-27",
            eligibleAmt: 1783.85,
            maxMaturityDate: "2025-04-27",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 12,
      arn: "2500011",
      bookingLocation: "SCB Hong Kong Ltd",
      workflowStage: "PRINP - Processing In-Progress",
      submissionMode: "OTC",
      receivedAt: "2024-02-06T11:38:39.000Z",
      __receivedAtMs: 1707219519000,
      createdAt: "2024-02-06T11:38:39.000Z",
      __createdAtMs: 1707219519000,
      updatedAt: "2024-02-06T11:38:39.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003140",
      customer: "100001111 - DEMO GROUP HOLDINGS",
      counterparty: "NG-Adaptor-IIF6",
      product: "SUF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201242",
      stage: "SPLCP - Split Completed",
      lli: "RISK",
      aml: "ZEKE",
      snc: "BOLT",
      clbk: "ECHO",
      cocoa: "RISK",
      tdOpsApproval: "NULL",
      customerRef: "NG-Adaptor-IIF6",
      regDate: "2024-02-06",
      relDate: "2024-02-06",
      segment: "ME",
      subSegment: "03",
      splitId: "253",
      sustainable: {
        sustainableFlag: false,
        classification: "",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "12-1",
          code: "E055",
          description: "Auto-generated exception E055 for TRN SPBTR25RFC003140",
          department: "Compliance",
        },
        {
          id: "12-2",
          code: "E001",
          description: "Auto-generated exception E001 for TRN SPBTR25RFC003140",
          department: "Operations",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "HKD",
        batchAmount: 1983.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "HKD",
        maxEligibleAmount: 1784.75,
        batchAdjustmentCurrency: "HKD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2024-02-06",
        statementDate: "2024-02-06",
        manualLLITrigger: false,
        documentNumber: "EIF_12_100xxxxxxxx",
        documentAmountCurrency: "HKD",
        documentAmount: 1983.05,
        adjustmentAmountCurrency: "HKD",
        adjustmentAmount: 0,
        counterpartyName: "NG-Adaptor-IIF6",
        documentIssueDate: "2024-02-06",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2024-02-13",
        incoterms: "FOB",
        eligibleAmountCurrency: "HKD",
        eligibleAmount: 1784.75,
        maxMaturityDate: "2024-02-13",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_12_100xxxxxxxx",
            currency: "HKD",
            amount: 1983.05,
            issueDate: "2024-02-06",
            dueDate: "2024-02-13",
            eligibleAmt: 1784.75,
            maxMaturityDate: "2024-02-13",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 13,
      arn: "2500012",
      bookingLocation: "Standard Chartered Bank (Singapore) Ltd",
      workflowStage: "TXPMK - Transaction Pending Maker",
      submissionMode: "EML",
      receivedAt: "2024-01-31T09:48:23.000Z",
      __receivedAtMs: 1706694503000,
      createdAt: "2024-01-31T09:48:23.000Z",
      __createdAtMs: 1706694503000,
      updatedAt: "2024-01-31T09:48:23.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003141",
      customer: "100006898 - TXOPT TESTING LONG NAME COMPANY LTD",
      counterparty: "PHARMA MED",
      product: "EIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201243",
      stage: "SPLIN - Split Initiated",
      lli: "ZEKE",
      aml: "BOLT",
      snc: "ECHO",
      clbk: "RISK",
      cocoa: "ZEKE",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2024-01-31",
      relDate: "2024-01-31",
      segment: "ME",
      subSegment: "03",
      splitId: "254",
      sustainable: {
        sustainableFlag: null,
        classification: "",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "13-1",
          code: "E055",
          description: "Auto-generated exception E055 for TRN SPBTR25RFC003141",
          department: "Compliance",
        },
        {
          id: "13-2",
          code: "E055",
          description: "Auto-generated exception E055 for TRN SPBTR25RFC003141",
          department: "Trade Services",
        },
        {
          id: "13-3",
          code: "E063",
          description: "Auto-generated exception E063 for TRN SPBTR25RFC003141",
          department: "Compliance",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "SGD",
        batchAmount: 1984.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "SGD",
        maxEligibleAmount: 1785.65,
        batchAdjustmentCurrency: "SGD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2024-01-31",
        statementDate: "2024-01-31",
        manualLLITrigger: false,
        documentNumber: "EIF_13_100xxxxxxxx",
        documentAmountCurrency: "SGD",
        documentAmount: 1984.05,
        adjustmentAmountCurrency: "SGD",
        adjustmentAmount: 0,
        counterpartyName: "PHARMA MED",
        documentIssueDate: "2024-01-31",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2024-02-07",
        incoterms: "FOB",
        eligibleAmountCurrency: "SGD",
        eligibleAmount: 1785.65,
        maxMaturityDate: "2024-02-07",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_13_100xxxxxxxx",
            currency: "SGD",
            amount: 1984.05,
            issueDate: "2024-01-31",
            dueDate: "2024-02-07",
            eligibleAmt: 1785.65,
            maxMaturityDate: "2024-02-07",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 14,
      arn: "2500013",
      bookingLocation: "SCB Malaysia Berhad",
      workflowStage: "PPRMK - Pre Processing Maker",
      submissionMode: "TNG",
      receivedAt: "2024-01-26T12:28:01.000Z",
      __receivedAtMs: 1706272081000,
      createdAt: "2024-01-26T12:28:01.000Z",
      __createdAtMs: 1706272081000,
      updatedAt: "2024-01-26T12:28:01.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003142",
      customer: "100009999 - SAMPLE INDUSTRIES PTE LTD",
      counterparty: "100502577 - TEST",
      product: "IIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201244",
      stage: "APRV - Approved",
      lli: "BOLT",
      aml: "ECHO",
      snc: "RISK",
      clbk: "ZEKE",
      cocoa: "BOLT",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2024-01-26",
      relDate: "2024-01-27",
      segment: "ME",
      subSegment: "03",
      splitId: "255",
      sustainable: {
        sustainableFlag: true,
        classification: "OTHERS",
        empoweredStatus: true,
        empoweredDate: "2024-01-26",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "MYR",
        batchAmount: 1978.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "MYR",
        maxEligibleAmount: 1780.25,
        batchAdjustmentCurrency: "MYR",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2024-01-26",
        statementDate: "2024-01-26",
        manualLLITrigger: false,
        documentNumber: "EIF_14_100xxxxxxxx",
        documentAmountCurrency: "MYR",
        documentAmount: 1978.05,
        adjustmentAmountCurrency: "MYR",
        adjustmentAmount: 0,
        counterpartyName: "100502577 - TEST",
        documentIssueDate: "2024-01-26",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2024-02-02",
        incoterms: "FOB",
        eligibleAmountCurrency: "MYR",
        eligibleAmount: 1780.25,
        maxMaturityDate: "2024-02-02",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_14_100xxxxxxxx",
            currency: "MYR",
            amount: 1978.05,
            issueDate: "2024-01-26",
            dueDate: "2024-02-02",
            eligibleAmt: 1780.25,
            maxMaturityDate: "2024-02-02",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 15,
      arn: "2500014",
      bookingLocation: "SCB Hong Kong Ltd",
      workflowStage: "SPLCP - Split Completed",
      submissionMode: "OTC",
      receivedAt: "2021-06-19T18:13:35.000Z",
      __receivedAtMs: 1624126415000,
      createdAt: "2021-06-19T18:13:35.000Z",
      __createdAtMs: 1624126415000,
      updatedAt: "2021-06-19T18:13:35.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003143",
      customer: "100001111 - DEMO GROUP HOLDINGS",
      counterparty: "NG-Adaptor-IIF6",
      product: "SUF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201245",
      stage: "EXEMK - Exception Handling Maker",
      lli: "ECHO",
      aml: "RISK",
      snc: "ZEKE",
      clbk: "BOLT",
      cocoa: "ECHO",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2021-06-19",
      relDate: "2021-06-20",
      segment: "ME",
      subSegment: "03",
      splitId: "256",
      sustainable: {
        sustainableFlag: true,
        classification: "TRANSITION",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "15-1",
          code: "E027",
          description: "Auto-generated exception E027 for TRN SPBTR25RFC003143",
          department: "Compliance",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "HKD",
        batchAmount: 1979.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "HKD",
        maxEligibleAmount: 1781.15,
        batchAdjustmentCurrency: "HKD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2021-06-19",
        statementDate: "2021-06-19",
        manualLLITrigger: false,
        documentNumber: "EIF_15_100xxxxxxxx",
        documentAmountCurrency: "HKD",
        documentAmount: 1979.05,
        adjustmentAmountCurrency: "HKD",
        adjustmentAmount: 0,
        counterpartyName: "NG-Adaptor-IIF6",
        documentIssueDate: "2021-06-19",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2021-06-26",
        incoterms: "FOB",
        eligibleAmountCurrency: "HKD",
        eligibleAmount: 1781.15,
        maxMaturityDate: "2021-06-26",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_15_100xxxxxxxx",
            currency: "HKD",
            amount: 1979.05,
            issueDate: "2021-06-19",
            dueDate: "2021-06-26",
            eligibleAmt: 1781.15,
            maxMaturityDate: "2021-06-26",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 16,
      arn: "2500015",
      bookingLocation: "Standard Chartered Bank (Singapore) Ltd",
      workflowStage: "SPLIN - Split Initiated",
      submissionMode: "EML",
      receivedAt: "2024-11-18T07:30:21.000Z",
      __receivedAtMs: 1731915021000,
      createdAt: "2024-11-18T07:30:21.000Z",
      __createdAtMs: 1731915021000,
      updatedAt: "2024-11-18T07:30:21.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003144",
      customer: "100006898 - TXOPT TESTING LONG NAME COMPANY LTD",
      counterparty: "PHARMA MED",
      product: "EIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201246",
      stage: "PRINP - Processing In-Progress",
      lli: "RISK",
      aml: "ZEKE",
      snc: "BOLT",
      clbk: "ECHO",
      cocoa: "RISK",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2024-11-18",
      relDate: "2024-11-19",
      segment: "ME",
      subSegment: "03",
      splitId: "257",
      sustainable: {
        sustainableFlag: true,
        classification: "SL",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "16-1",
          code: "E001",
          description: "Auto-generated exception E001 for TRN SPBTR25RFC003144",
          department: "Trade Services",
        },
        {
          id: "16-2",
          code: "E063",
          description: "Auto-generated exception E063 for TRN SPBTR25RFC003144",
          department: "Trade Services",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "SGD",
        batchAmount: 1980.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "SGD",
        maxEligibleAmount: 1782.05,
        batchAdjustmentCurrency: "SGD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2024-11-18",
        statementDate: "2024-11-18",
        manualLLITrigger: false,
        documentNumber: "EIF_16_100xxxxxxxx",
        documentAmountCurrency: "SGD",
        documentAmount: 1980.05,
        adjustmentAmountCurrency: "SGD",
        adjustmentAmount: 0,
        counterpartyName: "PHARMA MED",
        documentIssueDate: "2024-11-18",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2024-11-25",
        incoterms: "FOB",
        eligibleAmountCurrency: "SGD",
        eligibleAmount: 1782.05,
        maxMaturityDate: "2024-11-25",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_16_100xxxxxxxx",
            currency: "SGD",
            amount: 1980.05,
            issueDate: "2024-11-18",
            dueDate: "2024-11-25",
            eligibleAmt: 1782.05,
            maxMaturityDate: "2024-11-25",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 17,
      arn: "2500016",
      bookingLocation: "SCB Malaysia Berhad",
      workflowStage: "APRV - Approved",
      submissionMode: "TNG",
      receivedAt: "2022-12-11T22:10:46.000Z",
      __receivedAtMs: 1670796646000,
      createdAt: "2022-12-11T22:10:46.000Z",
      __createdAtMs: 1670796646000,
      updatedAt: "2022-12-11T22:10:46.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003145",
      customer: "100009999 - SAMPLE INDUSTRIES PTE LTD",
      counterparty: "100502577 - TEST",
      product: "IIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201247",
      stage: "TXPMK - Transaction Pending Maker",
      lli: "ZEKE",
      aml: "BOLT",
      snc: "ECHO",
      clbk: "RISK",
      cocoa: "ZEKE",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2022-12-11",
      relDate: "2022-12-12",
      segment: "ME",
      subSegment: "03",
      splitId: "258",
      sustainable: {
        sustainableFlag: false,
        classification: "",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "MYR",
        batchAmount: 1981.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "MYR",
        maxEligibleAmount: 1782.95,
        batchAdjustmentCurrency: "MYR",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2022-12-11",
        statementDate: "2022-12-11",
        manualLLITrigger: false,
        documentNumber: "EIF_17_100xxxxxxxx",
        documentAmountCurrency: "MYR",
        documentAmount: 1981.05,
        adjustmentAmountCurrency: "MYR",
        adjustmentAmount: 0,
        counterpartyName: "100502577 - TEST",
        documentIssueDate: "2022-12-11",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2022-12-18",
        incoterms: "FOB",
        eligibleAmountCurrency: "MYR",
        eligibleAmount: 1782.95,
        maxMaturityDate: "2022-12-18",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_17_100xxxxxxxx",
            currency: "MYR",
            amount: 1981.05,
            issueDate: "2022-12-11",
            dueDate: "2022-12-18",
            eligibleAmt: 1782.95,
            maxMaturityDate: "2022-12-18",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 18,
      arn: "2500017",
      bookingLocation: "SCB Hong Kong Ltd",
      workflowStage: "EXEMK - Exception Handling Maker",
      submissionMode: "OTC",
      receivedAt: "2022-09-24T12:51:12.000Z",
      __receivedAtMs: 1664023872000,
      createdAt: "2022-09-24T12:51:12.000Z",
      __createdAtMs: 1664023872000,
      updatedAt: "2022-09-24T12:51:12.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003146",
      customer: "100001111 - DEMO GROUP HOLDINGS",
      counterparty: "NG-Adaptor-IIF6",
      product: "SUF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201248",
      stage: "PPRMK - Pre Processing Maker",
      lli: "BOLT",
      aml: "ECHO",
      snc: "RISK",
      clbk: "ZEKE",
      cocoa: "BOLT",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2022-09-24",
      relDate: "2022-09-25",
      segment: "ME",
      subSegment: "03",
      splitId: "259",
      sustainable: {
        sustainableFlag: null,
        classification: "",
        empoweredStatus: null,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [
        {
          id: "18-1",
          code: "E027",
          description: "Auto-generated exception E027 for TRN SPBTR25RFC003146",
          department: "Credit Control",
        },
      ],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "HKD",
        batchAmount: 1982.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "HKD",
        maxEligibleAmount: 1783.85,
        batchAdjustmentCurrency: "HKD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2022-09-24",
        statementDate: "2022-09-24",
        manualLLITrigger: false,
        documentNumber: "EIF_18_100xxxxxxxx",
        documentAmountCurrency: "HKD",
        documentAmount: 1982.05,
        adjustmentAmountCurrency: "HKD",
        adjustmentAmount: 0,
        counterpartyName: "NG-Adaptor-IIF6",
        documentIssueDate: "2022-09-24",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2022-10-01",
        incoterms: "FOB",
        eligibleAmountCurrency: "HKD",
        eligibleAmount: 1783.85,
        maxMaturityDate: "2022-10-01",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_18_100xxxxxxxx",
            currency: "HKD",
            amount: 1982.05,
            issueDate: "2022-09-24",
            dueDate: "2022-10-01",
            eligibleAmt: 1783.85,
            maxMaturityDate: "2022-10-01",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 19,
      arn: "2500018",
      bookingLocation: "Standard Chartered Bank (Singapore) Ltd",
      workflowStage: "PRINP - Processing In-Progress",
      submissionMode: "EML",
      receivedAt: "2019-05-17T03:42:41.000Z",
      __receivedAtMs: 1558064561000,
      createdAt: "2019-05-17T03:42:41.000Z",
      __createdAtMs: 1558064561000,
      updatedAt: "2019-05-17T03:42:41.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003147",
      customer: "100006898 - TXOPT TESTING LONG NAME COMPANY LTD",
      counterparty: "PHARMA MED",
      product: "EIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201249",
      stage: "SPLCP - Split Completed",
      lli: "ECHO",
      aml: "RISK",
      snc: "ZEKE",
      clbk: "BOLT",
      cocoa: "ECHO",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2019-05-17",
      relDate: "2019-05-18",
      segment: "ME",
      subSegment: "03",
      splitId: "251",
      sustainable: {
        sustainableFlag: true,
        classification: "TRANSITION",
        empoweredStatus: null,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "SGD",
        batchAmount: 1983.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "SGD",
        maxEligibleAmount: 1784.75,
        batchAdjustmentCurrency: "SGD",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2019-05-17",
        statementDate: "2019-05-17",
        manualLLITrigger: false,
        documentNumber: "EIF_19_100xxxxxxxx",
        documentAmountCurrency: "SGD",
        documentAmount: 1983.05,
        adjustmentAmountCurrency: "SGD",
        adjustmentAmount: 0,
        counterpartyName: "PHARMA MED",
        documentIssueDate: "2019-05-17",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2019-05-24",
        incoterms: "FOB",
        eligibleAmountCurrency: "SGD",
        eligibleAmount: 1784.75,
        maxMaturityDate: "2019-05-24",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_19_100xxxxxxxx",
            currency: "SGD",
            amount: 1983.05,
            issueDate: "2019-05-17",
            dueDate: "2019-05-24",
            eligibleAmt: 1784.75,
            maxMaturityDate: "2019-05-24",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
    {
      id: 20,
      arn: "2500019",
      bookingLocation: "SCB Malaysia Berhad",
      workflowStage: "TXPMK - Transaction Pending Maker",
      submissionMode: "TNG",
      receivedAt: "2023-04-25T05:28:33.000Z",
      __receivedAtMs: 1682400513000,
      createdAt: "2023-04-25T05:28:33.000Z",
      __createdAtMs: 1682400513000,
      updatedAt: "2023-04-25T05:28:33.000Z",
      generatedBy: "System",
      trn: "SPBTR25RFC003148",
      customer: "100009999 - SAMPLE INDUSTRIES PTE LTD",
      counterparty: "100502577 - TEST",
      product: "IIF",
      step: "NEW001",
      subStep: "DRFF",
      lockedBy: "1201250",
      stage: "SPLIN - Split Initiated",
      lli: "RISK",
      aml: "ZEKE",
      snc: "BOLT",
      clbk: "ECHO",
      cocoa: "RISK",
      tdOpsApproval: "NULL",
      customerRef: "NG-STPAdaptor-EIF",
      regDate: "2023-04-25",
      relDate: "2023-04-26",
      segment: "ME",
      subSegment: "03",
      splitId: "252",
      sustainable: {
        sustainableFlag: null,
        classification: "",
        empoweredStatus: false,
        empoweredDate: "",
        remarks: "",
        othersSpecify: "",
      },
      exceptions: [],
      documents: {
        batchType: "INV - INVOICE",
        batchAmountCurrency: "MYR",
        batchAmount: 1984.05,
        batchCount: 1,
        nonFactored: false,
        maxEligibleCurrency: "MYR",
        maxEligibleAmount: 1785.65,
        batchAdjustmentCurrency: "MYR",
        batchAdjustmentAmount: 0,
        originalInvoiceSubmissionDate: "2023-04-25",
        statementDate: "2023-04-25",
        manualLLITrigger: false,
        documentNumber: "EIF_20_100xxxxxxxx",
        documentAmountCurrency: "MYR",
        documentAmount: 1984.05,
        adjustmentAmountCurrency: "MYR",
        adjustmentAmount: 0,
        counterpartyName: "100502577 - TEST",
        documentIssueDate: "2023-04-25",
        documentTenor: "30",
        paymentTerms: "NET30",
        documentDueDate: "2023-05-02",
        incoterms: "FOB",
        eligibleAmountCurrency: "MYR",
        eligibleAmount: 1785.65,
        maxMaturityDate: "2023-05-02",
        documentApprovalStatus: "APPR",
        overrideDocStatus: "",
        overrideReason: "",
        docDetailRows: [
          {
            number: "EIF_20_100xxxxxxxx",
            currency: "MYR",
            amount: 1984.05,
            issueDate: "2023-04-25",
            dueDate: "2023-05-02",
            eligibleAmt: 1785.65,
            maxMaturityDate: "2023-05-02",
            status: "ELGB",
          },
        ],
        goodsRows: [],
        partyRows: [],
        installmentRows: [],
      },
    },
  ],
  total: 4934,
};
